###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json


{
  "username": "ilves",
  "name" : "Kalle Lives",
  "password":"Allys"
}


###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json


{
  "username": "mm",
  "name" : "MManarwlh",
  "password":"mpd"
}


###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json


{

}

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json


{
  "username": "czisks",
  "name" : "Christos Ziskas",
  "password":"TUC"
}


###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json


{
  "username": "cre4t0r@yahoo.gr",
  "name" : "Chris Ziskas",
  "password":"nba"
}

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json


{
  "username": "cziskas@tuc.gr",
  "name" : "Ziskas Christos",
  "password":"nba"
}

###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json


{
  "username": "MManarwlh@apth.gr",
  "name" : "MM",
  "password":"mpd"
}