POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "author": "P.Ziskas",
  "url": "https://www.amazon.com",
  "title": "TUC",
  "likes": 0
}

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "author": "M.Manarwlh",
  "url": "https://www.instagram.com",
  "title": "Panepisthmio Aigiou"
}

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json


{
  "author": "E.Manarwlh",
  "url": "https://www.instagram.com",
  "title": "Panepisthmio Hrakleiou"
}

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json


{
  "author": "E.Manarwlh",
  "url": "https://www.instagram.com",
  "title": "Panepisthmio Hrakleiou",
  "likes" : 50
}

###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json


{
  "author": "E.Manarwlh",
  "likes" : 50
}

###  
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN6aXNrYXNAdHVjLmdyIiwiaWQiOjIsImlhdCI6MTY5MTQwMDY5NX0.xqtg8W4TU3IlmEpirkZsI2_CrGwigCQVQ9M9o-_UJcA

{
  "author": "E.Manarwlh",
  "url": "https://www.cretemarathon.com",
  "title": "Crete",
  "likes" : 1000
}

###  
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN6aXNrYXNAdHVjLmdyIiwiaWQiOjIsImlhdCI6MTY5MTQwMDY5NX0.xqtg8W4TU3IlmEpirkZsI2_CrGwigCQVQ9M9o-_UJcA

{
  "author": "MM.Manarwlh",
  "url": "https://www.cretemarathon.com",
  "title": "Katerini",
  "likes" : 10000
}


###
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1NYW5hcndsaEBhcHRoLmdyIiwiaWQiOjEsImlhdCI6MTY5MTQwMDY2NH0._fHIcHyYxh3IhshaMWKucLfaepmz3rg_wuf9-VH-rzU

{
  "author": "E.Manarwlh",
  "url": "https://www.cretemarathon.com",
  "title": "Crete",
  "likes" : 1000
}

###  
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1NYW5hcndsaEBhcHRoLmdyIiwiaWQiOjEsImlhdCI6MTY5MTQwMDY2NH0._fHIcHyYxh3IhshaMWKucLfaepmz3rg_wuf9-VH-rzU

{
  "author": "MM.Manarwlh",
  "url": "https://www.cretemarathon.com",
  "title": "Katerini",
  "likes" : 10000
}

###  
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1NYW5hcndsaEBhcHRoLmdyIiwiaWQiOjEsImlhdCI6MTY5MTQwMDY2NH0._fHIcHyYxh3IhshaMWKucLfaepmz3rg_wuf9-VH-rzU

{
  "author": "MM.Manarwlh",
  "url": "https://www.cretemarathon.com",
  "title": "Katerini",
  "likes" : 10001,
  "year" : 1997
}

###  
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1NYW5hcndsaEBhcHRoLmdyIiwiaWQiOjEsImlhdCI6MTY5MTQwMDY2NH0._fHIcHyYxh3IhshaMWKucLfaepmz3rg_wuf9-VH-rzU

{
  "author": "MM.Manarwlh",
  "url": "https://www.cretemarathon.com",
  "title": "Katerini",
  "likes" : 10001,
  "year" : 2040
}



