###
PUT http://localhost:3001/api/readinglists/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1NYW5hcndsaEBhcHRoLmdyIiwiaWQiOjEsImlhdCI6MTY5MTQwMDY2NH0._fHIcHyYxh3IhshaMWKucLfaepmz3rg_wuf9-VH-rzU
content-type: application/json

{  "read": "true" }

###
PUT http://localhost:3001/api/readinglists/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1NYW5hcndsaEBhcHRoLmdyIiwiaWQiOjEsImlhdCI6MTY5MTQwMDY2NH0._fHIcHyYxh3IhshaMWKucLfaepmz3rg_wuf9-VH-rzU
content-type: application/json

{  "read": "false" }