###
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "cziskas@tuc.gr",
    "password": "nba"
}


###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json


{
  "username": "MManarwlh@apth.gr",
  "password":"mpd"
}